spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/learn_spring-qa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
welcome:
  message: Welcome TheNeoPix again (qa) !!

management:
  endpoints:
    web:
      exposure:
        include: "*"